; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=powerpc-unknown-elf -mcpu=ppe42 < %s | FileCheck %s

; An i64 "r" inline-assembly operand must use a VDR tuple. In particular, the
; tuple chosen for %value must not overlap the live output pointer in r4.

define i32 @load_and_store(i32 %address, ptr %output) {
; CHECK-LABEL: load_and_store:
; CHECK:       # %bb.0:
; CHECK-NEXT:    #APP
; CHECK-NEXT:    lvd d8, 0(3)
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    #APP
; CHECK-NEXT:    stvd d8, 0(4)
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    li 3, 0
; CHECK-NEXT:    blr
  %value = tail call i64 asm sideeffect "lvd $0, 0($1)", "=r,b"(i32 %address)
  %stored = tail call i64 asm sideeffect "stvd $0, 0($2)", "=&r,0,b,~{memory}"(i64 %value, ptr %output)
  ret i32 0
}
